// GENERATED FILE — do not edit by hand.
// Offline catalogue of the sources AllRatesToday covers, mirrored from the
// site's src/data/central-banks.js. It exists so list_central_banks answers in
// keyless mode, where /api/v1/central-banks (which carries coverage dates and
// needs a key) is unavailable. Regenerate with scripts/gen-banks.mjs.

export interface BankCatalogEntry {
  code: string;
  name: string;
  country: string;
  home_ccy: string;
  kind: string;
  npm?: string;
}

export const BANK_CATALOG: BankCatalogEntry[] = [
  {"code":"fed","name":"US Federal Reserve (H.10)","country":"United States","home_ccy":"USD","kind":"central_bank","npm":"fed-exchange-rate"},
  {"code":"boe","name":"Bank of England","country":"United Kingdom","home_ccy":"GBP","kind":"central_bank","npm":"boe-exchange-rate"},
  {"code":"pboc","name":"People's Bank of China (CFETS)","country":"China","home_ccy":"CNY","kind":"central_bank","npm":"pboc-exchange-rate"},
  {"code":"rba","name":"Reserve Bank of Australia","country":"Australia","home_ccy":"AUD","kind":"central_bank","npm":"rba-exchange-rate"},
  {"code":"cbr","name":"Bank of Russia","country":"Russia","home_ccy":"RUB","kind":"central_bank","npm":"cbr-exchange-rate"},
  {"code":"tcmb","name":"Central Bank of Türkiye","country":"Türkiye","home_ccy":"TRY","kind":"central_bank","npm":"tcmb-exchange-rate"},
  {"code":"bcb","name":"Banco Central do Brasil (PTAX)","country":"Brazil","home_ccy":"BRL","kind":"central_bank","npm":"bcb-exchange-rate"},
  {"code":"bi","name":"Bank Indonesia","country":"Indonesia","home_ccy":"IDR","kind":"central_bank","npm":"bank-indonesia-exchange-rate"},
  {"code":"rbi","name":"Reserve Bank of India","country":"India","home_ccy":"INR","kind":"central_bank","npm":"rbi-exchange-rate"},
  {"code":"boc","name":"Bank of Canada","country":"Canada","home_ccy":"CAD","kind":"central_bank","npm":"boc-exchange-rate"},
  {"code":"bnm","name":"Bank Negara Malaysia","country":"Malaysia","home_ccy":"MYR","kind":"central_bank","npm":"bnm-exchange-rate"},
  {"code":"cbsl","name":"Central Bank of Sri Lanka","country":"Sri Lanka","home_ccy":"LKR","kind":"central_bank","npm":"cbsl-exchange-rate"},
  {"code":"cnb","name":"Czech National Bank","country":"Czech Republic","home_ccy":"CZK","kind":"central_bank","npm":"czech-national-bank-exchange-rate"},
  {"code":"ecb","name":"European Central Bank","country":"Eurozone","home_ccy":"EUR","kind":"central_bank","npm":"ecb-exchange-rate"},
  {"code":"nbp","name":"Narodowy Bank Polski","country":"Poland","home_ccy":"PLN","kind":"central_bank","npm":"nbp-exchange-rate"},
  {"code":"norges","name":"Norges Bank","country":"Norway","home_ccy":"NOK","kind":"central_bank","npm":"norges-bank-exchange-rate"},
  {"code":"riksbank","name":"Sveriges Riksbank","country":"Sweden","home_ccy":"SEK","kind":"central_bank","npm":"riksbank-exchange-rate"},
  {"code":"cbn","name":"Central Bank of Nigeria","country":"Nigeria","home_ccy":"NGN","kind":"central_bank","npm":"cbn-exchange-rate"},
  {"code":"cbk","name":"Central Bank of Kuwait","country":"Kuwait","home_ccy":"KWD","kind":"central_bank","npm":"cbk-exchange-rate"},
  {"code":"cbb","name":"Central Bank of Bahrain","country":"Bahrain","home_ccy":"BHD","kind":"central_bank","npm":"cbb-exchange-rate"},
  {"code":"cbar","name":"Central Bank of Azerbaijan","country":"Azerbaijan","home_ccy":"AZN","kind":"central_bank","npm":"cbar-exchange-rate"},
  {"code":"cbbh","name":"Central Bank of Bosnia and Herzegovina","country":"Bosnia and Herzegovina","home_ccy":"BAM","kind":"central_bank","npm":"cbbh-exchange-rate"},
  {"code":"bnb","name":"Bulgarian National Bank","country":"Bulgaria","home_ccy":"EUR","kind":"central_bank","npm":"bnb-exchange-rate"},
  {"code":"bcrp","name":"Central Reserve Bank of Peru","country":"Peru","home_ccy":"PEN","kind":"central_bank","npm":"bcrp-exchange-rate"},
  {"code":"boj","name":"Bank of Japan","country":"Japan","home_ccy":"JPY","kind":"central_bank","npm":"boj-exchange-rate"},
  {"code":"hkma","name":"Hong Kong Monetary Authority","country":"Hong Kong","home_ccy":"HKD","kind":"central_bank","npm":"hkma-exchange-rate"},
  {"code":"boi","name":"Bank of Israel","country":"Israel","home_ccy":"ILS","kind":"central_bank","npm":"bank-of-israel-exchange-rate"},
  {"code":"bcra","name":"Central Bank of Argentina","country":"Argentina","home_ccy":"ARS","kind":"central_bank","npm":"bcra-exchange-rate"},
  {"code":"sarb","name":"South African Reserve Bank","country":"South Africa","home_ccy":"ZAR","kind":"central_bank","npm":"sarb-exchange-rate"},
  {"code":"snb","name":"Swiss National Bank","country":"Switzerland","home_ccy":"CHF","kind":"central_bank","npm":"snb-exchange-rate"},
  {"code":"rbnz","name":"Reserve Bank of New Zealand","country":"New Zealand","home_ccy":"NZD","kind":"central_bank","npm":"rbnz-exchange-rate"},
  {"code":"bok","name":"Bank of Korea","country":"South Korea","home_ccy":"KRW","kind":"central_bank","npm":"bok-exchange-rate"},
  {"code":"bnr","name":"National Bank of Romania","country":"Romania","home_ccy":"RON","kind":"central_bank","npm":"bnr-exchange-rate"},
  {"code":"nbu","name":"National Bank of Ukraine","country":"Ukraine","home_ccy":"UAH","kind":"central_bank","npm":"nbu-exchange-rate"},
  {"code":"banxico","name":"Banco de México","country":"Mexico","home_ccy":"MXN","kind":"central_bank","npm":"banxico-exchange-rate"},
  {"code":"bsp","name":"Bangko Sentral ng Pilipinas","country":"Philippines","home_ccy":"PHP","kind":"central_bank","npm":"bsp-exchange-rate"},
  {"code":"bcrd","name":"Banco Central de la República Dominicana","country":"Dominican Republic","home_ccy":"DOP","kind":"central_bank","npm":"bcrd-exchange-rate"},
  {"code":"bcp","name":"Banco Central del Paraguay","country":"Paraguay","home_ccy":"PYG","kind":"central_bank","npm":"bcp-exchange-rate"},
  {"code":"nbc","name":"National Bank of Cambodia","country":"Cambodia","home_ccy":"KHR","kind":"central_bank","npm":"nbc-cambodia-exchange-rate"},
  {"code":"bog","name":"Bank of Ghana","country":"Ghana","home_ccy":"GHS","kind":"central_bank","npm":"bank-of-ghana-exchange-rate"},
  {"code":"cbe","name":"Central Bank of Egypt","country":"Egypt","home_ccy":"EGP","kind":"central_bank","npm":"cbe-exchange-rate"},
  {"code":"boa","name":"Bank of Albania","country":"Albania","home_ccy":"ALL","kind":"central_bank","npm":"bank-of-albania-exchange-rate"},
  {"code":"banguat","name":"Banco de Guatemala","country":"Guatemala","home_ccy":"GTQ","kind":"central_bank","npm":"banguat-exchange-rate"},
  {"code":"bom","name":"Bank of Mongolia","country":"Mongolia","home_ccy":"MNT","kind":"central_bank","npm":"bank-of-mongolia-exchange-rate"},
  {"code":"mas","name":"Monetary Authority of Singapore","country":"Singapore","home_ccy":"SGD","kind":"central_bank","npm":"mas-exchange-rate"},
  {"code":"bdi","name":"Banca d'Italia","country":"Italy","home_ccy":"EUR","kind":"central_bank","npm":"bdi-exchange-rate"},
  {"code":"dnb","name":"Danmarks Nationalbank","country":"Denmark","home_ccy":"DKK","kind":"central_bank","npm":"danmarks-nationalbank-exchange-rate"},
  {"code":"sfc","name":"Superintendencia Financiera de Colombia (TRM)","country":"Colombia","home_ccy":"COP","kind":"central_bank","npm":"colombia-trm-exchange-rate"},
  {"code":"nbk","name":"National Bank of Kazakhstan","country":"Kazakhstan","home_ccy":"KZT","kind":"central_bank","npm":"nbk-exchange-rate"},
  {"code":"nbg","name":"National Bank of Georgia","country":"Georgia","home_ccy":"GEL","kind":"central_bank","npm":"nbg-exchange-rate"},
  {"code":"cbu","name":"Central Bank of Uzbekistan","country":"Uzbekistan","home_ccy":"UZS","kind":"central_bank","npm":"cbu-exchange-rate"},
  {"code":"mnb","name":"Magyar Nemzeti Bank","country":"Hungary","home_ccy":"HUF","kind":"central_bank","npm":"magyar-nemzeti-bank-exchange-rate"},
  {"code":"cbi","name":"Central Bank of Iceland","country":"Iceland","home_ccy":"ISK","kind":"central_bank","npm":"central-bank-of-iceland-exchange-rate"},
  {"code":"cbuae","name":"Central Bank of the UAE","country":"United Arab Emirates","home_ccy":"AED","kind":"central_bank","npm":"cbuae-exchange-rate"},
  {"code":"sbp","name":"State Bank of Pakistan","country":"Pakistan","home_ccy":"PKR","kind":"central_bank","npm":"sbp-exchange-rate"},
  {"code":"nrb","name":"Nepal Rastra Bank","country":"Nepal","home_ccy":"NPR","kind":"central_bank","npm":"nrb-exchange-rate"},
  {"code":"cbj","name":"Central Bank of Jordan","country":"Jordan","home_ccy":"JOD","kind":"central_bank","npm":"cbj-exchange-rate"},
  {"code":"bb","name":"Bangladesh Bank","country":"Bangladesh","home_ccy":"BDT","kind":"central_bank","npm":"bangladesh-bank-exchange-rate"},
  {"code":"cbo","name":"Central Bank of Oman","country":"Oman","home_ccy":"OMR","kind":"central_bank","npm":"cbo-exchange-rate"},
  {"code":"pma","name":"Palestine Monetary Authority","country":"Palestine","home_ccy":"ILS","kind":"central_bank","npm":"palestine-monetary-authority-exchange-rate"},
  {"code":"cbm","name":"Central Bank of Myanmar","country":"Myanmar","home_ccy":"MMK","kind":"central_bank","npm":"cbm-exchange-rate"},
  {"code":"cbc","name":"Central Bank of the Republic of China (Taiwan)","country":"Taiwan","home_ccy":"TWD","kind":"central_bank","npm":"taiwan-central-bank-exchange-rate"},
  {"code":"bot","name":"Bank of Thailand","country":"Thailand","home_ccy":"THB","kind":"central_bank","npm":"bank-of-thailand-exchange-rate"},
  {"code":"amcm","name":"Monetary Authority of Macao","country":"Macao","home_ccy":"MOP","kind":"central_bank","npm":"amcm-exchange-rate"},
  {"code":"sbv","name":"State Bank of Vietnam","country":"Vietnam","home_ccy":"VND","kind":"central_bank","npm":"sbv-exchange-rate"},
  {"code":"bol","name":"Bank of the Lao PDR","country":"Laos","home_ccy":"LAK","kind":"central_bank","npm":"bank-of-laos-exchange-rate"},
  {"code":"bcv","name":"Central Bank of Venezuela","country":"Venezuela","home_ccy":"VES","kind":"central_bank","npm":"central-bank-of-venezuela-exchange-rate"},
  {"code":"bcch","name":"Central Bank of Chile","country":"Chile","home_ccy":"CLP","kind":"central_bank","npm":"central-bank-of-chile-exchange-rate"},
  {"code":"bcu","name":"Central Bank of Uruguay","country":"Uruguay","home_ccy":"UYU","kind":"central_bank","npm":"bcu-exchange-rate"},
  {"code":"bcbol","name":"Banco Central de Bolivia","country":"Bolivia","home_ccy":"BOB","kind":"central_bank","npm":"banco-central-de-bolivia-exchange-rate"},
  {"code":"cbvs","name":"Central Bank of Suriname","country":"Suriname","home_ccy":"SRD","kind":"central_bank","npm":"central-bank-of-suriname-exchange-rate"},
  {"code":"bogy","name":"Bank of Guyana","country":"Guyana","home_ccy":"GYD","kind":"central_bank","npm":"bank-of-guyana-exchange-rate"},
  {"code":"sama","name":"Saudi Central Bank (SAMA)","country":"Saudi Arabia","home_ccy":"SAR","kind":"central_bank","npm":"sama-exchange-rate"},
  {"code":"bam","name":"Bank Al-Maghrib","country":"Morocco","home_ccy":"MAD","kind":"central_bank","npm":"bank-al-maghrib-exchange-rate"},
  {"code":"nbs","name":"National Bank of Serbia","country":"Serbia","home_ccy":"RSD","kind":"central_bank","npm":"national-bank-of-serbia-exchange-rate"},
  {"code":"nbrb","name":"National Bank of the Republic of Belarus","country":"Belarus","home_ccy":"BYN","kind":"central_bank","npm":"nbrb-exchange-rate"},
  {"code":"qcb","name":"Qatar Central Bank","country":"Qatar","home_ccy":"QAR","kind":"central_bank","npm":"qcb-exchange-rate"},
  {"code":"cbiq","name":"Central Bank of Iraq","country":"Iraq","home_ccy":"IQD","kind":"central_bank","npm":"central-bank-of-iraq-exchange-rate"},
  {"code":"bda","name":"Bank of Algeria","country":"Algeria","home_ccy":"DZD","kind":"central_bank","npm":"bank-of-algeria-exchange-rate"},
  {"code":"bccr","name":"Banco Central de Costa Rica","country":"Costa Rica","home_ccy":"CRC","kind":"central_bank","npm":"bccr-exchange-rate"},
  {"code":"bceao","name":"Central Bank of West African States (BCEAO)","country":"West Africa (WAEMU)","home_ccy":"XOF","kind":"central_bank","npm":"bceao-exchange-rate"},
  {"code":"nbe","name":"National Bank of Ethiopia","country":"Ethiopia","home_ccy":"ETB","kind":"central_bank","npm":"national-bank-of-ethiopia-exchange-rate"},
  {"code":"cbke","name":"Central Bank of Kenya","country":"Kenya","home_ccy":"KES","kind":"central_bank","npm":"central-bank-of-kenya-exchange-rate"},
  {"code":"nbm","name":"National Bank of Moldova","country":"Moldova","home_ccy":"MDL","kind":"central_bank","npm":"nbm-exchange-rate"},
  {"code":"nbrm","name":"National Bank of North Macedonia","country":"North Macedonia","home_ccy":"MKD","kind":"central_bank","npm":"nbrm-exchange-rate"},
  {"code":"cba","name":"Central Bank of Armenia","country":"Armenia","home_ccy":"AMD","kind":"central_bank","npm":"cba-exchange-rate"},
  {"code":"beac","name":"Bank of Central African States (BEAC)","country":"Central Africa (CEMAC)","home_ccy":"XAF","kind":"central_bank","npm":"beac-exchange-rate"},
  {"code":"bct","name":"Central Bank of Tunisia","country":"Tunisia","home_ccy":"TND","kind":"central_bank","npm":"bct-exchange-rate"},
  {"code":"bnrw","name":"National Bank of Rwanda","country":"Rwanda","home_ccy":"RWF","kind":"central_bank","npm":"national-bank-of-rwanda-exchange-rate"},
  {"code":"bna","name":"National Bank of Angola","country":"Angola","home_ccy":"AOA","kind":"central_bank","npm":"bna-exchange-rate"},
  {"code":"botz","name":"Bank of Tanzania","country":"Tanzania","home_ccy":"TZS","kind":"central_bank","npm":"bank-of-tanzania-exchange-rate"},
  {"code":"bou","name":"Bank of Uganda","country":"Uganda","home_ccy":"UGX","kind":"central_bank","npm":"bou-exchange-rate"},
  {"code":"bojm","name":"Bank of Jamaica","country":"Jamaica","home_ccy":"JMD","kind":"central_bank","npm":"bank-of-jamaica-exchange-rate"},
  {"code":"bcn","name":"Banco Central de Nicaragua","country":"Nicaragua","home_ccy":"NIO","kind":"central_bank","npm":"bcn-exchange-rate"},
  {"code":"bch","name":"Banco Central de Honduras","country":"Honduras","home_ccy":"HNL","kind":"central_bank","npm":"bch-exchange-rate"},
  {"code":"cbtt","name":"Central Bank of Trinidad and Tobago","country":"Trinidad and Tobago","home_ccy":"TTD","kind":"central_bank","npm":"cbtt-exchange-rate"},
  {"code":"bmu","name":"Bank of Mauritius","country":"Mauritius","home_ccy":"MUR","kind":"central_bank","npm":"bmu-exchange-rate"},
  {"code":"bdm","name":"Banco de Moçambique","country":"Mozambique","home_ccy":"MZN","kind":"central_bank","npm":"bdm-exchange-rate"},
  {"code":"bob","name":"Bank of Botswana","country":"Botswana","home_ccy":"BWP","kind":"central_bank","npm":"bob-exchange-rate"},
  {"code":"boz","name":"Bank of Zambia","country":"Zambia","home_ccy":"ZMW","kind":"central_bank","npm":"boz-exchange-rate"},
  {"code":"rbm","name":"Reserve Bank of Malawi","country":"Malawi","home_ccy":"MWK","kind":"central_bank","npm":"rbm-exchange-rate"},
  {"code":"nbkr","name":"National Bank of the Kyrgyz Republic","country":"Kyrgyzstan","home_ccy":"KGS","kind":"central_bank","npm":"nbkr-exchange-rate"},
  {"code":"hmrc","name":"HM Revenue & Customs","country":"United Kingdom","home_ccy":"GBP","kind":"tax","npm":"hmrc-exchange-rate"},
  {"code":"bazg","name":"Swiss Federal Office for Customs and Border Security","country":"Switzerland","home_ccy":"CHF","kind":"tax","npm":"bazg-exchange-rate"},
  {"code":"ustreasury","name":"U.S. Department of the Treasury","country":"United States","home_ccy":"USD","kind":"tax","npm":"ustreasury-exchange-rate"},
  {"code":"composite","name":"Composite Official Rate","country":"Global","home_ccy":"USD","kind":"composite"},
];
